export const FETCH_SOCIAL_DATA_REQUEST = 'FETCH_SOCIAL_DATA_REQUEST';
export const FETCH_SOCIAL_DATA_SUCCESS = 'FETCH_SOCIAL_DATA_SUCCESS';
export const FETCH_SOCIAL_DATA_FAILURE = 'FETCH_SOCIAL_DATA_FAILURE';
